namespace Cod3rsGrowth.Dominio.Enums
{
    public enum Marcas
    {
        Audi,
        Bentley,
        BMW,
        Bugatti,
        Chevrolet,
        Ferrari,
        Fiat,
        Ford,
        Honda,
        Hyundai,
        Jaguar,
        Kia,
        Lamborghini,
        LandRover,
        Maserati,
        Mercedes,
        Mitsubishi,
        Nissan,
        Peugeot,
        Porsche,
        Renault,
        RollsRoyce,
        Subaru,
        Tesla,
        Toyota,
        Volkswagen
    }
}
