namespace Cod3rsGrowth.Dominio.Enums
{
    public enum Marcas
    {
        Toyota,
        Honda,
        Hyundai,
        Volkswagem,
        Chevrolet,
        Peugeot,
        Mercedes,
        Bmw,
        Mitsubishi,
        Ford,
        Audi,
        Nissan,
        Kia,
        Fiat,
        Renault,
        Subaru,
        Volvo,
        Jaguar,
        LandRover,
        Porsche,
        Tesla,
        Maserati,
        Ferrari,
        Lamborghini,
        Bentley,
        RollsRoyce,
        Bugatti
    }
}
